name: TypeScript

on:
  push:
    paths:
      - .github/workflows/typescript.yml
      - typescript/**

defaults:
  run:
    working-directory: typescript

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      - uses: actions/setup-node@v4
        name: Install NodeJS
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: typescript/package-lock.json
      - run: npm ci
        name: Install dependencies
      - run: npm test
        name: Run tests
      - run: npm run mutate
        name: Run mutation testing tool
      - uses: actions/upload-artifact@v4
        name: Typescript Report
        path: reports/mutation/mutation.html
        overwrite: true